[project]
name = "therapist"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "google-generativeai>=0.8.5",
    "gtts>=2.5.4",
    "langdetect>=1.0.9",
    "pillow>=11.3.0",
    "pygame>=2.6.1",
    "speechrecognition>=3.14.3",
]
